/*
 * generated by Xtext
 */
package de.gammarcraft.aqua.ui.contentassist

import de.gammarcraft.aqua.ui.contentassist.AbstractAquaProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class AquaProposalProvider extends AbstractAquaProposalProvider {
}
