/*
 * generated by Xtext
 */
package de.gammarcraft.aqua.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.gammarcraft.aqua.ui.internal.AquaActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AquaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AquaActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AquaActivator.getInstance().getInjector(AquaActivator.DE_GAMMARCRAFT_AQUA_AQUA);
	}
	
}
