/*
* generated by Xtext
*/
package de.gammarcraft.aqua.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.gammarcraft.aqua.services.AquaGrammarAccess;

public class AquaParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AquaGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.gammarcraft.aqua.parser.antlr.internal.InternalAquaParser createParser(XtextTokenStream stream) {
		return new de.gammarcraft.aqua.parser.antlr.internal.InternalAquaParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "AquaModel";
	}
	
	public AquaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AquaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
