/*
* generated by Xtext
*/
package de.gammarcraft.aqua.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class AquaAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/gammarcraft/aqua/parser/antlr/internal/InternalAqua.tokens");
	}
}
