/*
 * generated by Xtext
 */
package de.gammarcraft.aqua.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AquaUiModule extends de.gammarcraft.aqua.ui.AbstractAquaUiModule {
	public AquaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
