/*
* generated by Xtext
*/
package de.gammarcraft.aqua;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class AquaStandaloneSetup extends AquaStandaloneSetupGenerated{

	public static void doSetup() {
		new AquaStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

