/*
 * generated by Xtext
 */
package de.gammarcraft.aqua;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AquaRuntimeModule extends de.gammarcraft.aqua.AbstractAquaRuntimeModule {

}
