/*
* generated by Xtext
*/
package de.gammarcraft.aqua;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class AquaUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.gammarcraft.aqua.ui.internal.AquaActivator.getInstance().getInjector("de.gammarcraft.aqua.Aqua");
	}
	
}
